vse: &vse
  docker:
    - image: circleci/node:8.11.3

version: 2.1
jobs:
  build:
    <<: *vse
    steps:
      - checkout
      - run: npm install
      - run: npm run test
      - run: npm run build
      - persist_to_workspace:
         root: .
         paths:
            - .
  deploy:
    <<: *vse
    docker:
      - image: 'circleci/python:latest'
    steps:
   # Installation
      - run:
         name: Install System Packages
         command: pip install --upgrade pip && pip install ansible
      - run:
         name: Install other
         command: sudo pip install boto boto3
      - run:
         name: Run playbook
         command: ansible-playbook ../ec2_deploy.yml --user ubuntu --key-file ../test.pem

workflows:
  version: 2.1
  build:
    jobs:
      - build
      - deploy:
         requires:
            - build
         filters:
            branches:
               only: master
